before_install:
  - gem install bundler

rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.8
  - 2.3.5
  - 2.4.4
  - 2.5.1
  - ruby-head
  - rbx
  - jruby

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-4.2.x
  - gemfiles/Gemfile.rails-5.0.x
  - gemfiles/Gemfile.rails-5.1.x
  - gemfiles/Gemfile.rails-master

matrix:
  exclude:
    # Rails 5+ requires Ruby >= 2.2.2
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-master
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-master
    - rvm: 2.2.8
      gemfile: gemfiles/Gemfile.rails-master
    - rvm: 2.3.5
      gemfile: gemfiles/Gemfile.rails-master
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-5.0.x
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5.0.x
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-5.1.x
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5.1.x
  allow_failures:
    - rvm: rbx
    - rvm: jruby
  fast_finish: true
