before_install: "sudo apt-get install ruby-tokyocabinet -y"

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - rbx
  - jruby

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x

matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby
  fast_finish: true
