rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ree
  - rbx
  - jruby

matrix:
  - rvm: 1.8.7
    gemfile: ci/Gemfile.rails-3.x
  - rvm: 1.9.2
    gemfile: ci/Gemfile.rails-3.x
  - rvm: 1.9.3
    gemfile: ci/Gemfile.rails-3.x
